# Pandas Essential

In [1]:
import pandas as pd

## 1. Series

In [4]:
x =[1,2,3,4]
var = pd.Series(x,index=['a','b','c','d'],dtype='float',name='python')

print(var)
print(type(var))
print(var[2])

print()

# for Dictionary
dic={'name':['python','c','c++'],'popularity':[16,32,22],'rank':[1,3,2]}
var1=pd.Series(dic)
print(var1)

a    1.0
b    2.0
c    3.0
d    4.0
Name: python, dtype: float64
<class 'pandas.core.series.Series'>
3.0

name          [python, c, c++]
popularity        [16, 32, 22]
rank                 [1, 3, 2]
dtype: object

/tmp/ipykernel_22945/3349020544.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[2])

In [5]:
s = pd.Series(12)
print(type(s),s)

# with index
s = pd.Series(12,index=[1,2,3,4,5,6])
print(type(s),s)

s1 = pd.Series(12,index=[1,2,3,4,5,6,7,8,9])
s2 = pd.Series(12,index=[1,2,3,4])

print(s1+s2)
# benefit of pandas  over numpy is we can perform operation on missing data
# and in numpy if try it shows the broadcasting error

<class 'pandas.core.series.Series'> 0    12
dtype: int64
<class 'pandas.core.series.Series'> 1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64
1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

## 2.DataFrame

In [7]:
# list
l=[1,2,3,4,5,6]
var= pd.DataFrame(l)
print(type(var),var)

#dict
d={'a':[1,2,3],'s':[4,5,6]}
var1 =pd.DataFrame(d)
print(type(var1),var1)
var1 =pd.DataFrame(d,columns=['a'],index=['A','B','C'])
print(var1)

<class 'pandas.core.frame.DataFrame'>    0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>    a  s
0  1  4
1  2  5
2  3  6
   a
A  1
B  2
C  3

In [8]:
#dict
d={'a':[1,2,3],'s':[4,5,6]}
var1 =pd.DataFrame(d)
print(var1)
print()
print(var1['s'][2])

#list
list_1=[[1,23,45,6,45],[66,88,2,56,46]]
var2 =pd.DataFrame(list_1)
print(var2)

#series
sr ={'s':pd.Series([1,2,3,4]),'r':pd.Series([1,2,3,4])}
var3 =pd.DataFrame(sr)
print(var3)
print(type(var3))

   a  s
0  1  4
1  2  5
2  3  6

6
    0   1   2   3   4
0   1  23  45   6  45
1  66  88   2  56  46
   s  r
0  1  1
1  2  2
2  3  3
3  4  4
<class 'pandas.core.frame.DataFrame'>

## 3.Arithemetic Operations

In [9]:
var=pd.DataFrame({'A':[1,2,3],'B':[5,6,7]})
print(var)

var['C']=var["A"]+var['B']
print(var)

var['C']=var["A"]-var['B']
print(var)

var['C']=var["A"]*var['B']
print(var)

var['C']=var["A"]/var['B']
print(var)

var1=pd.DataFrame({'a':[10,20,30,40],'b':[60,9,33,65]})
print(var1)
var1['python']=var1['a']<=30
var1['c++']=var1['b']%2==0

print(var1)

   A  B
0  1  5
1  2  6
2  3  7
   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
    a   b
0  10  60
1  20   9
2  30  33
3  40  65
    a   b  python    c++
0  10  60    True   True
1  20   9    True  False
2  30  33    True  False
3  40  65   False  False

## 4.Delete and Insert Data

In [10]:
# Insert

#create a dataframe
var =pd.DataFrame({'a':[1,2,3,4,5,],'b':[6,7,8,9,10]})

var.insert(1,'python',var['a'])

# data passsed by list
var.insert(1,'python_1',[11,12,13,14,15])

#copy the limited amount of data
var["python_2"]=var['a'][:3]
var# in this way we can add another column

   a  python_1  python   b  python_2
0  1        11       1   6       1.0
1  2        12       2   7       2.0
2  3        13       3   8       3.0
3  4        14       4   9       NaN
4  5        15       5  10       NaN

In [11]:
# Delete
var_1 =pd.DataFrame({'a':[1,2,3,4,5,],'b':[6,7,8,9,10]})
var_2=var_1.pop('b')
var_2

0     6
1     7
2     8
3     9
4    10
Name: b, dtype: int64

In [12]:
var_1

   a
0  1
1  2
2  3
3  4
4  5

In [13]:
var12 =pd.DataFrame({'a':[1,2,3,4,5,],'b':[6,7,8,9,10]})
del var12['b']
var12

   a
0  1
1  2
2  3
3  4
4  5

## 5.CSV file handling

In [14]:
data= {'a':[1,2,3,4,5,],'b':[6,7,8,9,10],'c':[11,12,13,14,15]}
d=pd.DataFrame(data)

print(d)

d.to_csv("test.csv",index=False,header=['p','q','r'])

   a   b   c
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [15]:
# read the csv
csv_1=pd.read_csv("DATASET/economy.csv")
print(csv_1)

              date   airline ch_code  num_code dep_time     from time_taken  \
0       11-02-2022  SpiceJet      SG      8709    18:55    Delhi    02h 10m
1       11-02-2022  SpiceJet      SG      8157    06:20    Delhi    02h 20m
2       11-02-2022   AirAsia      I5       764    04:25    Delhi    02h 10m
3       11-02-2022   Vistara      UK       995    10:20    Delhi    02h 15m
4       11-02-2022   Vistara      UK       963    08:50    Delhi    02h 20m
...            ...       ...     ...       ...      ...      ...        ...
206769  31-03-2022   Vistara      UK       832    07:05  Chennai    13h 50m
206770  31-03-2022   Vistara      UK       832    07:05  Chennai    13h 50m
206771  31-03-2022   Vistara      UK       826    12:30  Chennai    20h 35m
206772  31-03-2022   Vistara      UK       822    09:45  Chennai    23h 20m
206773  31-03-2022   Vistara      UK       824    20:30  Chennai    24h 25m

                                                     stop arr_time         to  \
0                                               non-stop     21:05     Mumbai
1                                               non-stop     08:40     Mumbai
2                                               non-stop     06:35     Mumbai
3                                               non-stop     12:35     Mumbai
4                                               non-stop     11:10     Mumbai
...                                                   ...      ...        ...
206769  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:55  Hyderabad
206770  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:55  Hyderabad
206771  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    09:05  Hyderabad
206772  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    09:05  Hyderabad
206773  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:55  Hyderabad

        price
0       5,953
1       5,953
2       5,956
3       5,955
4       5,955
...       ...
206769  7,697
206770  7,709
206771  8,640
206772  8,640
206773  8,640

[206774 rows x 11 columns]

In [ ]:
# nrows
csv_2=pd.read_csv("DATASET/economy.csv",nrows=2)
print(csv_2)
print(type(csv_2))

In [16]:
# Usecols function
csv_2=pd.read_csv("DATASET/economy.csv",usecols=['airline'])
print(csv_2)
print(type(csv_2))

         airline
0       SpiceJet
1       SpiceJet
2        AirAsia
3        Vistara
4        Vistara
...          ...
206769   Vistara
206770   Vistara
206771   Vistara
206772   Vistara
206773   Vistara

[206774 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>

In [17]:
# you can get the column with the help of column's index number 

csv_2=pd.read_csv("DATASET/economy.csv",usecols=[0,2])
print(csv_2)
print(type(csv_2))

              date ch_code
0       11-02-2022      SG
1       11-02-2022      SG
2       11-02-2022      I5
3       11-02-2022      UK
4       11-02-2022      UK
...            ...     ...
206769  31-03-2022      UK
206770  31-03-2022      UK
206771  31-03-2022      UK
206772  31-03-2022      UK
206773  31-03-2022      UK

[206774 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>

In [18]:
# skip function
csv_3=pd.read_csv("DATASET/economy.csv",skiprows=[0,2,9])
print(csv_3)
print(type(csv_3))

        11-02-2022 SpiceJet  SG  8709  18:55    Delhi  02h 10m  \
0       11-02-2022  AirAsia  I5   764  04:25    Delhi  02h 10m
1       11-02-2022  Vistara  UK   995  10:20    Delhi  02h 15m
2       11-02-2022  Vistara  UK   963  08:50    Delhi  02h 20m
3       11-02-2022  Vistara  UK   945  11:40    Delhi  02h 20m
4       11-02-2022  Vistara  UK   927  09:30    Delhi  02h 05m
...            ...      ...  ..   ...    ...      ...      ...
206766  31-03-2022  Vistara  UK   832  07:05  Chennai  13h 50m
206767  31-03-2022  Vistara  UK   832  07:05  Chennai  13h 50m
206768  31-03-2022  Vistara  UK   826  12:30  Chennai  20h 35m
206769  31-03-2022  Vistara  UK   822  09:45  Chennai  23h 20m
206770  31-03-2022  Vistara  UK   824  20:30  Chennai  24h 25m

                                                non-stop   21:05     Mumbai  \
0                                               non-stop   06:35     Mumbai
1                                               non-stop   12:35     Mumbai
2                                               non-stop   11:10     Mumbai
3                                               non-stop   14:00     Mumbai
4                                               non-stop   11:35     Mumbai
...                                                   ...    ...        ...
206766  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...  20:55  Hyderabad
206767  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...  20:55  Hyderabad
206768  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...  09:05  Hyderabad
206769  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...  09:05  Hyderabad
206770  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...  20:55  Hyderabad

        5,953
0       5,956
1       5,955
2       5,955
3       5,955
4       6,060
...       ...
206766  7,697
206767  7,709
206768  8,640
206769  8,640
206770  8,640

[206771 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>

In [20]:
#index call
csv_4=pd.read_csv(r"DATASET/economy.csv",index_col='num_code')
csv_4

,date,airline,ch_code,dep_time,from,time_taken,stop,arr_time,to,price
num_code,,,,,,,,,,
8709,11-02-2022,SpiceJet,SG,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
8157,11-02-2022,SpiceJet,SG,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
764,11-02-2022,AirAsia,I5,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
995,11-02-2022,Vistara,UK,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
963,11-02-2022,Vistara,UK,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955"
...,...,...,...,...,...,...,...,...,...,...
832,31-03-2022,Vistara,UK,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,697"
832,31-03-2022,Vistara,UK,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,709"
826,31-03-2022,Vistara,UK,12:30,Chennai,20h 35m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
822,31-03-2022,Vistara,UK,09:45,Chennai,23h 20m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
824,31-03-2022,Vistara,UK,20:30,Chennai,24h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"8,640"

In [21]:
# header function

csv_5=pd.read_csv("DATASET/economy.csv",header=2)
csv_5

,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
0,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
1,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
2,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955"
3,11-02-2022,Vistara,UK,945,11:40,Delhi,02h 20m,non-stop,14:00,Mumbai,"5,955"
4,11-02-2022,Vistara,UK,927,09:30,Delhi,02h 05m,non-stop,11:35,Mumbai,"6,060"
...,...,...,...,...,...,...,...,...,...,...,...
206767,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,697"
206768,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,709"
206769,31-03-2022,Vistara,UK,826,12:30,Chennai,20h 35m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206770,31-03-2022,Vistara,UK,822,09:45,Chennai,23h 20m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206771,31-03-2022,Vistara,UK,824,20:30,Chennai,24h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"8,640"

In [22]:
csv_4=pd.read_csv("DATASET/economy.csv",names=['col1','col2','col3','col4','col5','col6','col7'])
csv_4

/tmp/ipykernel_22945/1224823879.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  csv_4=pd.read_csv("DATASET/economy.csv",names=['col1','col2','col3','col4','col5','col6','col7'])

                                          col1     col2        col3  \
date       airline  ch_code num_code  dep_time     from  time_taken
11-02-2022 SpiceJet SG      8709         18:55    Delhi     02h 10m
                            8157         06:20    Delhi     02h 20m
           AirAsia  I5      764          04:25    Delhi     02h 10m
           Vistara  UK      995          10:20    Delhi     02h 15m
...                                        ...      ...         ...
31-03-2022 Vistara  UK      832          07:05  Chennai     13h 50m
                            832          07:05  Chennai     13h 50m
                            826          12:30  Chennai     20h 35m
                            822          09:45  Chennai     23h 20m
                            824          20:30  Chennai     24h 25m

                                                                                   col4  \
date       airline  ch_code num_code                                               stop
11-02-2022 SpiceJet SG      8709                                              non-stop
                            8157                                              non-stop
           AirAsia  I5      764                                               non-stop
           Vistara  UK      995                                               non-stop
...                                                                                 ...
31-03-2022 Vistara  UK      832       1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...
                            832       1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...
                            826       1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...
                            822       1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...
                            824       1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...

                                          col5       col6   col7
date       airline  ch_code num_code  arr_time         to  price
11-02-2022 SpiceJet SG      8709         21:05     Mumbai  5,953
                            8157         08:40     Mumbai  5,953
           AirAsia  I5      764          06:35     Mumbai  5,956
           Vistara  UK      995          12:35     Mumbai  5,955
...                                        ...        ...    ...
31-03-2022 Vistara  UK      832          20:55  Hyderabad  7,697
                            832          20:55  Hyderabad  7,709
                            826          09:05  Hyderabad  8,640
                            822          09:05  Hyderabad  8,640
                            824          20:55  Hyderabad  8,640

[206775 rows x 7 columns]

In [23]:
# how to remove header 
csv_5=pd.read_csv("DATASET/economy.csv",header= None)
csv_5

/tmp/ipykernel_22945/2918651900.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  csv_5=pd.read_csv("DATASET/economy.csv",header= None)

,0,1,2,3,4,5,6,7,8,9,10
0,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
1,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
2,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
3,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
4,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
...,...,...,...,...,...,...,...,...,...,...,...
206770,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,697"
206771,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,709"
206772,31-03-2022,Vistara,UK,826,12:30,Chennai,20h 35m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206773,31-03-2022,Vistara,UK,822,09:45,Chennai,23h 20m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206774,31-03-2022,Vistara,UK,824,20:30,Chennai,24h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"8,640"

In [24]:
csv_4=pd.read_csv("DATASET/economy.csv",dtype={'num_code':'float'})
csv_4

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,SpiceJet,SG,8709.0,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
1,11-02-2022,SpiceJet,SG,8157.0,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
2,11-02-2022,AirAsia,I5,764.0,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
3,11-02-2022,Vistara,UK,995.0,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
4,11-02-2022,Vistara,UK,963.0,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955"
...,...,...,...,...,...,...,...,...,...,...,...
206769,31-03-2022,Vistara,UK,832.0,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,697"
206770,31-03-2022,Vistara,UK,832.0,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,709"
206771,31-03-2022,Vistara,UK,826.0,12:30,Chennai,20h 35m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206772,31-03-2022,Vistara,UK,822.0,09:45,Chennai,23h 20m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206773,31-03-2022,Vistara,UK,824.0,20:30,Chennai,24h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"8,640"

## 6. Functions Related to CSV file

In [28]:
import numpy as np
import pandas as pd
csv_5=pd.read_csv("DATASET/winequality-red.csv")

In [29]:
print(csv_5.index)
print(csv_5.columns)
print(csv_5.describe())
print(csv_5.head())
print(csv_5.head(2))
print(csv_5.tail())
print(csv_5.tail(10))
print(csv_5[:5])
print(csv_5.index.array)
print(csv_5.to_numpy())

v= np.asarray(csv_5)
print(v)

RangeIndex(start=0, stop=1599, step=1)
Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000
mean        8.319637          0.527821     0.270976        2.538806
std         1.741096          0.179060     0.194801        1.409928
min         4.600000          0.120000     0.000000        0.900000
25%         7.100000          0.390000     0.090000        1.900000
50%         7.900000          0.520000     0.260000        2.200000
75%         9.200000          0.640000     0.420000        2.600000
max        15.900000          1.580000     1.000000       15.500000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000
mean      0.087467            15.874922             46.467792     0.996747
std       0.047065            10.460157             32.895324     0.001887
min       0.012000             1.000000              6.000000     0.990070
25%       0.070000             7.000000             22.000000     0.995600
50%       0.079000            14.000000             38.000000     0.996750
75%       0.090000            21.000000             62.000000     0.997835
max       0.611000            72.000000            289.000000     1.003690

                pH    sulphates      alcohol      quality
count  1599.000000  1599.000000  1599.000000  1599.000000
mean      3.311113     0.658149    10.422983     5.636023
std       0.154386     0.169507     1.065668     0.807569
min       2.740000     0.330000     8.400000     3.000000
25%       3.210000     0.550000     9.500000     5.000000
50%       3.310000     0.620000    10.200000     6.000000
75%       3.400000     0.730000    11.100000     6.000000
max       4.010000     2.000000    14.900000     8.000000
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality
0      9.4        5
1      9.8        5
2      9.8        5
3      9.8        6
4      9.4        5
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076
1            7.8              0.88          0.0             2.6      0.098

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68

   alcohol  quality
0      9.4        5
1      9.8        5
      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090
1595            5.9             0.550         0.10             2.2      0.062
1596            6.3             0.510         0.13             2.3      0.076
1597            5.9             0.645         0.12             2.0      0.075
1598            6.0             0.310         0.47             3.6      0.067

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58
1595                 39.0                  51.0  0.99512  3.52       0.76
1596                 29.0                  40.0  0.99574  3.42       0.75
1597                 32.0                  44.0  0.99547  3.57       0.71
1598                 18.0                  42.0  0.99549  3.39       0.66

      alcohol  quality
1594     10.5        5
1595     11.2        6
1596     11.0        6
1597     10.2        5
1598     11.0        6
      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1589            6.6             0.725         0.20             7.8      0.073
1590            6.3             0.550         0.15             1.8      0.077
1591            5.4             0.740         0.09             1.7      0.089
1592            6.3             0.510         0.13             2.3      0.076
1593            6.8             0.620         0.08             1.9      0.068
1594            6.2             0.600         0.08             2.0      0.090
1595            5.9             0.550         0.10             2.2      0.062
1596            6.3             0.510         0.13             2.3      0.076
1597            5.9             0.645         0.12             2.0      0.075
1598            6.0             0.310         0.47             3.6      0.067

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1589                 29.0                  79.0  0.99770  3.29       0.54
1590                 26.0                  35.0  0.99314  3.32       0.82
1591                 16.0                  26.0  0.99402  3.67       0.56
1592                 29.0                  40.0  0.99574  3.42       0.75
1593                 28.0                  38.0  0.99651  3.42       0.82
1594                 32.0                  44.0  0.99490  3.45       0.58
1595                 39.0                  51.0  0.99512  3.52       0.76
1596                 29.0                  40.0  0.99574  3.42       0.75
1597                 32.0                  44.0  0.99547  3.57       0.71
1598                 18.0                  42.0  0.99549  3.39       0.66

      alcohol  quality
1589      9.2        5
1590     11.6        6
1591     11.6        6
1592     11.0        6
1593      9.5        6
1594     10.5        5
1595     11.2        6
1596     11.0        6
1597     10.2        5
1598     11.0        6
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality
0      9.4        5
1      9.8        5
2      9.8        5
3      9.8        6
4      9.4        5
<NumpyExtensionArray>
[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
 ...
 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598]
Length: 1599, dtype: int64
[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]

In [30]:
v= np.asarray(csv_5)
print(v)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]

In [31]:
csv_5.sort_index(axis=0,ascending= False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5

In [32]:
# change data
csv_5.loc[0,'Name']='tushar'
csv_5

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

In [33]:
csv_5.loc[[0,3],['density','pH']]
# in this way we can get data of specific location

   density    pH
0   0.9978  3.51
3   0.9980  3.16

In [34]:
csv_5.loc[:,['density','pH']]

      density    pH
0     0.99780  3.51
1     0.99680  3.20
2     0.99700  3.26
3     0.99800  3.16
4     0.99780  3.51
...       ...   ...
1594  0.99490  3.45
1595  0.99512  3.52
1596  0.99574  3.42
1597  0.99547  3.57
1598  0.99549  3.39

[1599 rows x 2 columns]

In [35]:
csv_5.loc[[0,3],:]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,tushar
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,NaN

In [36]:
csv_5.iloc[2,1]
# 2 is index number  and 1 is column

np.float64(0.76)

In [37]:
# if you want to drop the specific data then you have to use the drop function
# this is for column
csv_5.drop('Name',axis=1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [38]:
# for rows 
csv_5.drop(5,axis=0)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

## 7.Replace

In [39]:
csv_5.replace(to_replace='sulphates	',value='9.9')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

In [40]:
csv_5.replace([101,102,103,104,105,106,107,108,109],'NEW')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

In [42]:
csv_5.replace("[A-Z a-z]",'chlorides',regex=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,chlorideschlorideschlorideschlorideschloridesc...
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

# syntax
csv_5.replace(data,method='bfill')
# limit function
csv_5.replace([],method='ffill',limit=3,inplace=True)

## 8.Interpolate

In [43]:
# to fill missing values we use interpolate function
csv_5.interpolate()
# this function only work on numeric values it can not fill string values 
#it fill data in linear fashion by default

/tmp/ipykernel_22945/2687689862.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_5.interpolate()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

csv_5.interpolate(method='linear',axis=1)

csv_5.interpolate(limit_direction='forward',limit=3)
# we can use backeard,both

csv_5.interpolate(limit_area='inside')
# fill inside blank data

csv_6.interpolate(limit_area='outside')
# gives  remaining none values

## 9.Merge Function

In [49]:
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
var2=pd.DataFrame({'A':[1,2,3],"C":[44,55,66]})

pd.merge(var1,var2,on="A")

   A  B   C
0  1  4  44
1  2  5  55
2  3  6  66

In [46]:
# how parameter= handling ,missing data in different dataframes

#left
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
var2=pd.DataFrame({'A':[1,2,5],"C":[44,55,66]})

pd.merge(var1,var2,how='left')

   A  B     C
0  1  4  44.0
1  2  5  55.0
2  3  6   NaN

In [47]:
# right
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
var2=pd.DataFrame({'A':[1,2,5],"C":[44,55,66]})

pd.merge(var1,var2,how='right')

   A    B   C
0  1  4.0  44
1  2  5.0  55
2  5  NaN  66

In [48]:
# outer
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
var2=pd.DataFrame({'A':[1,2,5],"C":[44,55,66]})

pd.merge(var1,var2,how='outer',indicator=True)

   A    B     C      _merge
0  1  4.0  44.0        both
1  2  5.0  55.0        both
2  3  6.0   NaN   left_only
3  5  NaN  66.0  right_only

In [50]:
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
var2=pd.DataFrame({'A':[1,2,5],'B':[44,55,66]})

pd.merge(var1,var2,left_index=True,right_index=True,suffixes=('name','id'))

   Aname  Bname  Aid  Bid
0      1      4    1   44
1      2      5    2   55
2      3      6    5   66

## 10. Cocatenation

In [52]:
import pandas as pd
import numpy as np

In [53]:
sr1 = pd.Series([1,2,3])
sr2 = pd.Series([4,5,6,7])

pd.concat([sr1,sr2])

0    1
1    2
2    3
0    4
1    5
2    6
3    7
dtype: int64

In [54]:
d1=pd.DataFrame({'A':[1,2,5,6]})
d2=pd.DataFrame({'B':[9,87]})
pd.concat([d1,d2],join='outer')

     A     B
0  1.0   NaN
1  2.0   NaN
2  5.0   NaN
3  6.0   NaN
0  NaN   9.0
1  NaN  87.0

In [55]:
d1=pd.DataFrame({'A':[1,2,5,6]})
d2=pd.DataFrame({'B':[9,87]})
pd.concat([d1,d2],join='inner',axis=1)

   A   B
0  1   9
1  2  87

In [56]:
d1=pd.DataFrame({'A':[1,2,5,6]})
d2=pd.DataFrame({'B':[9,87]})
pd.concat([d1,d2],keys=['d1','d2'])

        A     B
d1 0  1.0   NaN
   1  2.0   NaN
   2  5.0   NaN
   3  6.0   NaN
d2 0  NaN   9.0
   1  NaN  87.0

## 11.Group by function

In [57]:
import pandas as pd
import numpy as np
import random

In [58]:
var=np.random.randint(1,100,10 )
var

array([18, 72, 86, 58, 80, 26, 24,  4,  2, 71])

In [60]:
var =pd.DataFrame({'name':['a','b','c','d','a','a'],
                   'marks1':[18, 72, 86, 58, 80, 26],
                   'marks2':[26, 24,  4,  2, 71,66]})

In [61]:
var_new =var.groupby('name')
var_new

In [62]:
for x,y in var_new:
    print(x)
    print(y)
    print()

a
  name  marks1  marks2
0    a      18      26
4    a      80      71
5    a      26      66

b
  name  marks1  marks2
1    b      72      24

c
  name  marks1  marks2
2    c      86       4

d
  name  marks1  marks2
3    d      58       2

In [63]:
var_new.get_group('a')

  name  marks1  marks2
0    a      18      26
4    a      80      71
5    a      26      66

In [64]:
var_new.min()

      marks1  marks2
name
a         18      26
b         72      24
c         86       4
d         58       2

In [65]:
var_new.max()

      marks1  marks2
name
a         80      71
b         72      24
c         86       4
d         58       2

In [66]:
var_new.mean()

         marks1     marks2
name
a     41.333333  54.333333
b     72.000000  24.000000
c     86.000000   4.000000
d     58.000000   2.000000

In [67]:
var_new.median()

      marks1  marks2
name
a       26.0    66.0
b       72.0    24.0
c       86.0     4.0
d       58.0     2.0

In [68]:
li=list(var_new)
li

[('a',
    name  marks1  marks2
  0    a      18      26
  4    a      80      71
  5    a      26      66),
 ('b',
    name  marks1  marks2
  1    b      72      24),
 ('c',
    name  marks1  marks2
  2    c      86       4),
 ('d',
    name  marks1  marks2
  3    d      58       2)]

## 12.join and append function

In [69]:
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]},index=['a','b','c'])
var2=pd.DataFrame({'C':[7,8,9],'D':[10,11,12]},index=['a','b','c'])

var2.join(var2,how='inner',lsuffix='_11',rsuffix='_12')

   C_11  D_11  C_12  D_12
a     7    10     7    10
b     8    11     8    11
c     9    12     9    12

In [70]:
var1.join(var2)

   A  B  C   D
a  1  4  7  10
b  2  5  8  11
c  3  6  9  12

In [71]:
# Append
var1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
var2=pd.DataFrame({'C':[11,22,33,44,55],'D':[44,55,66,77,88]})

var1.append(var2)
# it is removed from pandas instead of this use concat function

AttributeError: 'DataFrame' object has no attribute 'append'

In [72]:
import pandas as pd

var1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
var2 = pd.DataFrame({'C': [11, 22, 33, 44, 55], 'D': [44, 55, 66, 77, 88]})

result = pd.concat([var1, var2], axis=0)  # axis=0 means stacking vertically
print(result)

     A    B     C     D
0  1.0  4.0   NaN   NaN
1  2.0  5.0   NaN   NaN
2  3.0  6.0   NaN   NaN
0  NaN  NaN  11.0  44.0
1  NaN  NaN  22.0  55.0
2  NaN  NaN  33.0  66.0
3  NaN  NaN  44.0  77.0
4  NaN  NaN  55.0  88.0

## 13.Melt Funnction

In [73]:
var =pd.DataFrame({'days':[1,2],'english':[10,11],'math':[14,15]})
var

   days  english  math
0     1       10    14
1     2       11    15

In [74]:
pd.melt(var)# reshape the dataframe

  variable  value
0     days      1
1     days      2
2  english     10
3  english     11
4     math     14
5     math     15

In [75]:
pd.melt(var,id_vars=['days'])

   days variable  value
0     1  english     10
1     2  english     11
2     1     math     14
3     2     math     15

In [76]:
pd.melt(var,id_vars=['days'],var_name='subject',value_name='marks')

   days  subject  marks
0     1  english     10
1     2  english     11
2     1     math     14
3     2     math     15

## 14.Pivot function

In [78]:
var1 =pd.DataFrame({'days':[1,2,3,4,5],'english':[10,11,12,13,14],'student':['a','b','c','d','e'],'marks':[14,15,16,18,19]})
var1

   days  english student  marks
0     1       10       a     14
1     2       11       b     15
2     3       12       c     16
3     4       13       d     18
4     5       14       e     19

In [79]:
var1.pivot(index='days',columns='english',values='marks')

english    10    11    12    13    14
days
1        14.0   NaN   NaN   NaN   NaN
2         NaN  15.0   NaN   NaN   NaN
3         NaN   NaN  16.0   NaN   NaN
4         NaN   NaN   NaN  18.0   NaN
5         NaN   NaN   NaN   NaN  19.0

In [81]:
var1.pivot_table(index='days',columns='marks')
# aggfunc ,margins are discarded

TypeError: agg function failed [how->mean,dtype->object]

## 15.Dropna and Fillna

In [82]:
csv_5.dropna()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.7,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,tushar

In [83]:
csv_5.dropna(axis=1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [84]:
# to remove particular row
csv_5.dropna(how='all')
# remove row having all nan values

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

# to remone null along particular column
csv.dropna(subset=['COL_NAME'])

csv.dropna(inplace=True)
csv

In [86]:
csv_5.dropna(thresh=3)
# jiske andar 3 null value hai use remove karega

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,NaN
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,NaN
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,NaN
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,NaN
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,NaN
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,NaN
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,NaN

In [87]:
csv_5.fillna('python')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,tushar
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,python
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,python
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,python
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,python
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,python
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,python
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,python
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,python
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,python

csv_test.fillna({'Salary':'python','JoiningDate':'java'})

csv_test.fillna(method='ffill')

csv_test.fillna(method='bfill')